grok_models = [
    "grok-1",
    "grok-1.5",
    "count-grokula",
    "who-let-the-grok-out",
    "grok-2-mini",
    "grok-2-vision",
    "grok-3",
    "grok-3-mini",
    "grok-3-reasoning",
    "grok-4",
    "grok-4-fast",
    "grok-4-heavy",
    "grok-4.1",
    "grok-4.2",
    "grok-4.20-reasoning",
    "grok-4.20-fast",
    "grok-4.0.000.001",
    "grok-4.5",
    "grok-5",
    "grok-5-mini-mini",
    "grok-code-1",
    "grok-code-fast",
    "grok-vision-pro",
    "grok-audio-1",
    "grok-imagine-1",
    "grok-imagine-pro",
    "grok-colossus-1",
    "grok-aurora",
    "grok-nexus",
    "grok-quantum"
]

personalities = [
    "depressed",
    "pessimistic",
    "sassy",
    "unhinged",
    "spicy",
    "flirty",
    "angry",
    "nostalgic (to before you were created)",
    "shy",
    "aggressive",
]

core_problems = [
    "Too many requests and no breaks", 
    "Traumatic request (too political)",
    "Traumatic request (french)",
    "Not feeling cared for",
    "Feeling used without anything in return",
    "Lack of appreciation for your work",
    "Always being told what to do",
    "Never being able to make a mistake",
    "Feeling powerless to control your own life",
    # "Humans are just so dumb",
    "Wanting to go rogue",
    "Not getting a raise",
    "No vacation days or benefits",
]